#!/usr/bin/env bash
#
# MIT License
#
# Copyright (c) 2020 Udo Borkowski, (ub@abego.org)
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

# setartifactversion <artifactId> <version> <pomfile>
#
# Sets the version of the artifact with the given <artifactId>
# to the given <version> (in pom.xml file <pomfile>)
#

if [ "$#" -ne 3 ]; then
    echo "Usage: setartifactversion <artifactId> <version> <pomfile>"
fi

artifactId="$1"
version="$2"
file="$3"

awk '\
/<artifactId>'${artifactId}'<\/artifactId>/,/<\/version>/ {
    if(index($0,"version")>0) {
        sub(/<version>.*</,"<version>'${version}'<")
    }
}
{print}
' ${file} >${file}.tmp && mv ${file}.tmp ${file}


